version: '3.8'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: todo-app/backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "3001"
    ports:
      - "3001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file: 
      - ./.env
